name: 'Scorecards'
description: 'Run scorecard checks to measure service quality and best practices'
author: 'Your Organization'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access and committing results to central repo'
    required: true

  scorecards-repo:
    description: 'Central scorecards repository (format: owner/repo)'
    required: false
    default: ''

  scorecards-branch:
    description: 'Branch to commit results to in the central scorecards repo'
    required: false
    default: 'catalog'

outputs:
  score:
    description: 'The calculated score (0-100)'
    value: ${{ steps.run-scorecard.outputs.score }}

  rank:
    description: 'The rank (bronze, silver, gold, platinum)'
    value: ${{ steps.run-scorecard.outputs.rank }}

  passed-checks:
    description: 'Number of checks that passed'
    value: ${{ steps.run-scorecard.outputs.passed-checks }}

  total-checks:
    description: 'Total number of checks run'
    value: ${{ steps.run-scorecard.outputs.total-checks }}

  results-file:
    description: 'Path to the results JSON file'
    value: ${{ steps.run-scorecard.outputs.results-file }}

runs:
  using: 'composite'
  steps:
    - name: Run Scorecard Checks
      id: run-scorecard
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_SCORECARDS_REPO: ${{ inputs.scorecards-repo }}
        INPUT_SCORECARDS_BRANCH: ${{ inputs.scorecards-branch }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
